### ISSUE TITLE
[configure script] The information about CXX is not printed

### ISSUE THREAD

**Issue by iahunq** [JulNadeauCA/BSDBuild#1]
Only the information about CC is printed even though my project is 100% C++. I tried to put `require(cxx)` on `configure.in` but that doesn't help. But it seems the configure script really probed the information about CXX, it only doesn't print them on the screen. I guess it's the case because I tried to put a target on `Makefile` to print the value of `CXX`. It printed `g++`.

**Comment by JulNadeauCA** [comment]
I'm unable to reproduce this with the latest version. I made a minimal `configure.in` that contained only `require(cxx)` and it printed out the value of `CXX` as expected:
`
$ ./configure
BSDBuild 3.2 <https://bsdbuild.hypertriton.com/>
* Overwriting existing Makefile.config
checking for a C++ compiler...yes, /usr/bin/clang++
checking whether the C++ compiler works...yes
cxx: checking for compiler warning options...yes
**
** Configuration successful!
**
** Use "make depend all" to compile. When finished,
** run "make install" to install under /usr/local.
**
`
