### ISSUE TITLE
`configure.lua` will grow indefinitely large if you run the configure script multiple times

### ISSUE THREAD

**Issue by iahunq** [JulNadeauCA/BSDBuild#2]
This is because the configure script will append to it instead of overwriting it. I checked the configure script, it uses `>>` (append) instead of `>` (overwrite).

**Comment by JulNadeauCA** [comment]
Good catch! This has been fixed in the development version. Also, `configure.lua` is no longer generated by default at all. It was only used for project file generation with `build.proj.mk` (now deprecated in favor of cmake).
