### ISSUE TITLE
Add `cxx_*` functions to deal with C++

### ISSUE THREAD

**Issue by iahunq** [JulNadeauCA/BSDBuild#4]
On the document of `mkconfigure`:

http://bsdbuild.hypertriton.com/man1/mkconfigure

I found you are mixing C and C++ into only one set of `c_*` functions. This will sooner or later turn into a mess.

**Comment by JulNadeauCA** [comment]
Directives such as `c_define()` are used to set C-style definitions at the project level. Despite their naming, they really have nothing to do with the C compiler or the language used by your project. Those C-style definitions can be used from C, C++, Objective C, Lua, Cmake, etc.

**Comment by iahung2** [comment]
> Directives such as `c_define()` are used to set C-style definitions at the project level.

The OP is talking about all of the `c_*` functions, not only `c_define()`. C and C++ are different language. There are flags that you want for C but not for C++ and vice versa. You are forcing the same flags for both C and C++. This is not something good to do.

**Comment by JulNadeauCA** [comment]
Oh, I see what you mean and I agree.

Commit https://github.com/JulNadeauCA/BSDBuild/commit/68a3037775cbb3a643dbecb1a1aa815b582d0ed7 should address this. It introduces new directives `cxx_define()`, `cxx_incdir()`, `cxx_option()`, `check_cxx_header()`, `check_cxx_header_opts()` and `check_cxx_func_opts()` where the tests are performed in C++. Also, `c_define()` no longer appends to `CXXFLAGS`.
